site_name: ludwikc.net / pov 
site_url: https://ludwikc.net
docs_dir: ludwikc-pov

exclude_docs:
  ludwikc-pov/private/
  ludwikc-pov/personal/
  ludwikc-pov/.trash/
  ludwikc-pov/_templates/

theme:
  favicon: assets/images/favicon.png
  name: material
  language: en
  icon:
#    logo: logo
    annotation: material/eye-circle
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: 
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.tooltips
    - content.action.edit

repo_url: https://github.com/ludwikc/ludwikc.github.io
repo_name: ludwikc.net/pov

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-CGKPMN1HP1 
    feedback:
      title: Czy to było ciekawe?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Dzięki!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ludwikc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ludwikc
  generator: false

plugins:
#  - search
#      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-committers:
      repository: ludwikc/ludwikc.github.io
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - pub-obsidian:
      obsidian_dir: .obsidian
      links:
        wikilinks_enabled: true
        img_lazy: true
  - pub-meta:
      publish:
        file_default: draft
        file_warn_on_missing: true
        dir_default: published
      title:
        key_name: title
      overview:
        default: auto
        key_name: permalink
  - pub-blog:
      teaser_marker: "<!-- more -->"
      searchable_non_posts: false
      posts_per_page: 5
      slug: blog
  - pub-social:
      site_name_in_title:
        location: after
        delimiter: " - "
  - glightbox
  

copyright: |
  &copy; 2024 <a href="https://siadlak.com"  target="_blank" rel="noopener">Ludwik C. Siadlak</a>
